### ISSUE TITLE
Better Documentation on Card properties.

### ISSUE THREAD

**Issue by BaReinhard** [googlesamples/hangouts-chat-samples#2]
It would be nice to see a definitive list of what other objects can be used in, widgets, cards, etc. It may be that the docs show everything possible, but I haven't seen any documentation stating that is the case or that its not the case.

**Comment by erickoledadevrel** [comment]
FYI, to best way report an issue with our documentation please use the "Send Feedback" button on the upper-right-hand side of the page.

The reference documentation includes a complete list of the types and fields available:

https://developers.google.com/hangouts/chat/reference/rest/v1/cards

**Comment by BaReinhard** [comment]
My apologies. Thank you for the reference. Ill be sure to bookmark this link.
